### ISSUE TITLE
App crashes when saving after setting alarm

### ISSUE THREAD

**Issue by Marzhel** [overlevelsesguiden/The10H-Android#15]
When adding a new plan or editing an existing one, the app crashes when saving after adding an alarm

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dk.overlevelsesguiden.de10her, PID: 9162
    java.lang.IllegalArgumentException: dk.overlevelsesguiden.de10her: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at dk.overlevelsesguiden.de10her.presentation.fragments.QuestionLayoutFragment.setAlarm(QuestionLayout.kt:110)
        at dk.overlevelsesguiden.de10her.presentation.fragments.UpdateDocumentFragment.prepareDocumentForUpdate(UpdateDocumentFragment.kt:212)
        at dk.overlevelsesguiden.de10her.presentation.fragments.UpdateDocumentFragment.updateDocument(UpdateDocumentFragment.kt:227)
        at dk.overlevelsesguiden.de10her.presentation.fragments.UpdateDocumentFragment.setupToolbar$lambda-6$lambda-5(UpdateDocumentFragment.kt:182)
        at dk.overlevelsesguiden.de10her.presentation.fragments.UpdateDocumentFragment.$r8$lambda$NjTTjMZqDDWr-bCY7VWe2o7rIic(Unknown Source:0)
        at dk.overlevelsesguiden.de10her.presentation.fragments.UpdateDocumentFragment$$ExternalSyntheticLambda2.onMenuItemClick(Unknown Source:2)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:7441)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/985236f1a89c7df541331ecb6e29498c3bfb74c0
