### ISSUE TITLE
Crash when changing notification time

### ISSUE THREAD

**Issue by Marzhel** [overlevelsesguiden/The10H-Android#21]
If I edit a plan and sets a notification, saves it, taps edit again and set a new notification time, the app will crash when saving the plan.

I also noticed the new notification time I chose didn't show in the alert window

Let me know if you need more details

```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: dk.overlevelsesguiden.de10her, PID: 25783
    java.lang.IllegalStateException: Method addObserver must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
        at androidx.lifecycle.SavedStateHandleController.attachToLifecycle(SavedStateHandleController.java:49)
        at androidx.lifecycle.SavedStateHandleController.attachHandleIfNeeded(SavedStateHandleController.java:101)
        at androidx.lifecycle.SavedStateViewModelFactory.onRequery(SavedStateViewModelFactory.java:167)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:175)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at dk.overlevelsesguiden.de10her.presentation.fragments.QuestionLayoutFragment.getDocumentViewModel(QuestionLayout.kt:43)
        at dk.overlevelsesguiden.de10her.presentation.fragments.QuestionLayoutFragment$setAlarm$2.invokeSuspend(QuestionLayout.kt:119)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Marzhel** [comment]
It seems like it's not always. I have attached a video that shows it crashing.

It also looks like the date picker is not set to the notification time when editing (The view with the big round clock thingy)

https://www.dropbox.com/s/m0wbda8sdepqk62/22-03-17-20-19-23.mp4?dl=0

**Comment by Albyzai** [comment]
The datepicker notification time has been fixed. I have not been able to replicate the crash, but in the notification commit I also switched to using dependency injection for the ViewModel, which may have fixed this issue.

Let me know if you are still able to replicate it. The latest version is up now.
