### ISSUE TITLE
App crashes when notification time has arrived

### ISSUE THREAD

**Issue by Marzhel** [overlevelsesguiden/The10H-Android#23]
Steps to reproduce:

1. Start the app
2. Write a plan with notification ON to be triggered in 1 min
3. Save the plan
4. Wait 1 min

Log that might be related?

```
2022-03-27 19:42:04.889 2364-2792/? W/SHANNON_IMS: 3855 [RULE] Wait for QNS broadcast for VoWiFi registration. Current: 3 (WiFiConnectivity%isValidConnection:147)
2022-03-27 19:42:04.890 2364-2792/? W/SHANNON_IMS: 3856 [RULE] VOC is NOT ready, isValidConnection() is false [WiFiConnectivity  STATE:trueSLID:0 ] (WiFiConnectivity%isVocReady:69)
2022-03-27 19:42:04.987 2364-2792/? E/SHANNON_IMS: 3873 [CONN] Registration lock interrupted (ImsConnectivityMgr%triggerRegistering:2933)
    android.net.ConnectivityManager$TooManyRequestsException
        at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:3771)
        at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3960)
        at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3967)
        at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4349)
        at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4319)
        at com.shannon.imsservice.conn.ApnManager.enableApn(ApnManager.java:112)
        at com.shannon.imsservice.conn.ImsConnectivityMgr.sendRegistration(ImsConnectivityMgr.java:3186)
        at com.shannon.imsservice.conn.ImsConnectivityMgr.triggerRegisteringImsDeregistered(ImsConnectivityMgr.java:3046)
        at com.shannon.imsservice.conn.ImsConnectivityMgr.triggerRegistering(ImsConnectivityMgr.java:2926)
        at com.shannon.imsservice.conn.ImsConnectivityMgr.triggerRegistering(ImsConnectivityMgr.java:2866)
        at com.shannon.imsservice.conn.ImsConnectivityMgr$ImsRegistrationTimerTask.run(ImsConnectivityMgr.java:3713)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)
2022-03-27 19:42:05.151 1521-1567/? W/System: A resource failed to call close. 
2022-03-27 19:42:05.152 1521-1567/? W/System: A resource failed to call release. 
2022-03-27 19:42:05.152 1521-1567/? W/System: A resource failed to call close. 
2022-03-27 19:42:05.152 1521-1567/? W/System: A resource failed to call close. 
2022-03-27 19:42:05.152 1521-1567/? W/System: A resource failed to call close. 
2022-03-27 19:42:07.696 24196-24257/? E/bluetooth: system/bt/bta/dm/bta_dm_pm.cc:1035 bta_dm_pm_btm_status: Received unknown power mode status event:5
2022-03-27 19:42:09.363 19775-19882/? W/CAM_A: Ignoring metadata for image that is not in supported location: /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Images/IMG-20160226-WA0002.jpg
2022-03-27 19:42:11.279 19775-19882/? W/CAM_A: Ignoring metadata for image that is not in supported location: /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Images/IMG-20160611-WA0000.jpg
2022-03-27 19:42:14.911 2364-2792/? W/SHANNON_IMS: 3877 [RULE] Wait for QNS broadcast for VoWiFi registration. Current: 3 (WiFiConnectivity%isValidConnection:147)
2022-03-27 19:42:14.912 2364-2792/? W/SHANNON_IMS: 3878 [RULE] VOC is NOT ready, isValidConnection() is false [WiFiConnectivity  STATE:trueSLID:0 ] (WiFiConnectivity%isVocReady:69)
2022-03-27 19:42:15.041 2364-2792/? E/SHANNON_IMS: 3895 [CONN] Registration lock interrupted (ImsConnectivityMgr%triggerRegistering:2933)
```

Reported by Ziv

**Comment by Albyzai** [comment]
I was not able to reproduce this error. But I encountered a crash caused by one of the recent changes, which i fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/77eeaa1448a034bdc397d16e47262c9b565de17a

**Comment by Marzhel** [comment]
I tried to re-produce it on a OnePlus and it worked fine for me. Closing for now
