### ISSUE TITLE
App crashes if two plans are tapped on at the same time

### ISSUE THREAD

**Issue by Marzhel** [overlevelsesguiden/The10H-Android#27]
Here's the crash trace

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dk.overlevelsesguiden.de10her, PID: 9786
    java.lang.IllegalArgumentException: Navigation action/destination dk.overlevelsesguiden.de10her:id/action_documentListFragment_to_documentDetails cannot be found from the current destination Destination(dk.overlevelsesguiden.de10her:id/documentDetails) label={title} class=dk.overlevelsesguiden.de10her.presentation.fragments.DocumentDetailsFragment
        at androidx.navigation.NavController.navigate(NavController.java:940)
        at androidx.navigation.NavController.navigate(NavController.java:877)
        at androidx.navigation.NavController.navigate(NavController.java:863)
        at androidx.navigation.NavController.navigate(NavController.java:1159)
        at dk.overlevelsesguiden.de10her.presentation.DocumentListAdapter$ViewHolder.bind$lambda-1(DocumentListAdapter.kt:62)
        at dk.overlevelsesguiden.de10her.presentation.DocumentListAdapter$ViewHolder.$r8$lambda$ioqXnLyUJ3rCXVIig_pyuT-uRqI(Unknown Source:0)
        at dk.overlevelsesguiden.de10her.presentation.DocumentListAdapter$ViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7520)
        at android.view.View.performClickInternal(View.java:7489)
        at android.view.View.access$3600(View.java:826)
        at android.view.View$PerformClick.run(View.java:28555)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/aa872a9714c87201d2ee69b0c49805e1a6b50492
